function out1 = getCenter(R,x0,x1,y0,y1)
%getCenter
%    OUT1 = getCenter(R,X0,X1,Y0,Y1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Oct-2022 12:44:20

t2 = R.^2;
t3 = x0.*2.0;
t4 = x1.*2.0;
t5 = x0.^2;
t6 = x1.^2;
t7 = y0.^2;
t8 = y1.^2;
t10 = y0.*y1.*2.0;
t13 = x0.*x1.*-2.0;
t15 = y0./2.0;
t16 = y1./2.0;
t9 = t3.*x1;
t11 = -t4;
t12 = t2.*4.0;
t14 = -t10;
t18 = -t5;
t19 = -t7;
t17 = -t12;
t20 = t3+t11;
t22 = t5+t6+t7+t8+t13+t14;
t21 = 1.0./t20;
t23 = 1.0./t22;
t24 = t17+t22;
t25 = t23.*t24;
t26 = -t25;
t27 = sqrt(t26);
t28 = (t27.*x0)./2.0;
t29 = (t27.*x1)./2.0;
t30 = -t28;
t31 = -t29;
t32 = t15+t16+t29+t30;
t33 = t15+t16+t28+t31;
out1 = reshape([t21.*(t5-t6+t7-t8-t32.*y0.*2.0+t32.*y1.*2.0),t21.*(t5-t6+t7-t8-t33.*y0.*2.0+t33.*y1.*2.0),t32,t33],[2,2]);
