function [q1,q2,q3,q4] = tf2qPincher(theta,x,y,z)
%tf2qPincher
%    [Q1,Q2,Q3,Q4] = tf2qPincher(THETA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    25-Oct-2022 11:25:05

t2 = cos(theta);
t3 = sin(theta);
t4 = x.^2;
t5 = y.^2;
t6 = z.^2;
t8 = z.*2.06e+2;
t24 = z.*8.99641890121408e-3;
t7 = t2.^2;
t9 = -t4;
t10 = -t5;
t11 = -t6;
t12 = t3.*1.1e+2;
t13 = -t8;
t14 = t4+t5;
t15 = t3.*z.*2.2e+2;
t16 = t3.*2.266e+4;
t20 = t4./2.2898e+4;
t21 = t5./2.2898e+4;
t22 = t6./2.2898e+4;
t26 = -t24;
t27 = t3.*z.*9.607826011005328e-3;
t28 = t3.*9.896060791335488e-1;
t17 = -t15;
t18 = -t16;
t19 = t7.*1.21e+4;
t23 = sqrt(t14);
q1 = angle(-((t2.*1.1e+2-t23).*(x+y.*1i))./t23);
if nargout > 1
    t25 = t12+z-1.03e+2;
    t29 = -t28;
    t30 = t2.*t23.*2.2e+2;
    t32 = t2.*t23.*9.607826011005328e-3;
    t31 = -t30;
    t33 = -t32;
    t40 = t8+t9+t10+t11+t16+t17+t30+1.89e+2;
    t34 = t14+t19+t31;
    t38 = t6+t13+t14+t15+t18+t31+2.2709e+4;
    t41 = t40.^2;
    t45 = t20+t21+t22+t26+t27+t29+t33-8.25399598218185e-3;
    t35 = 1.0./sqrt(t34);
    t39 = 1.0./t38;
    t42 = -t41;
    t46 = acos(t45);
    t36 = t25.*t35;
    t43 = t42+5.24318404e+8;
    t37 = atan(t36);
    t44 = sqrt(t43);
    t47 = t39.*t44;
    t48 = atan(t47);
    q2 = t37+t48-pi./2.0;
end
if nargout > 2
    q3 = -t46;
end
if nargout > 3
    q4 = -t37+t46-t48;
end
